### ISSUE TITLE
关于您博客 Travis CI 总是更新旧文章的问题

### ISSUE THREAD

**Issue by wafer-li** [sli1989/sli1989.github.io#1]
你好，首先十分感谢你提供了使用 Travis CI 进行博客自动构建的 idea 给我。

在查看你的博客和源码之后，我发现你的博客存在一个我之前比较头痛，但最终被我解决的问题：

首先 master 的 commit 历史只有两个；

其次即使你没有更新过的旧博客，它的更新时间都变成最新的了；

对于这种问题，我写了[一篇博客](https://wafer.li/Hexo/%E8%A7%A3%E5%86%B3%20Travis%20CI%20%E6%80%BB%E6%98%AF%E6%9B%B4%E6%96%B0%E6%97%A7%E5%8D%9A%E5%AE%A2%E7%9A%84%E9%97%AE%E9%A2%98/)来描述原因和解决方法。

敬请参考。

**Comment by sli1989** [comment]
好，谢谢，这个我倒是不怎么介意，gitlab有commit历史。
PS 用https方式 只有一个commit历史。
解决了倒是蛮好。我也去学习下。

---
另外，应该可以生成deploy密匙和公匙进行SSH连接。看你[文章](https://wafer.li/Hexo/Hexo%20%E9%9B%86%E6%88%90%20Travis%20CI%20%E8%87%AA%E5%8A%A8%E9%83%A8%E7%BD%B2%E5%8D%9A%E6%96%87/)里面没有改。

**Comment by wafer-li** [comment]
我是采用 personal access token 的形式进行部署的，不知道采用 

> 生成deploy密匙和公匙进行SSH连接。

这种方法有什么好处？

**Comment by sli1989** [comment]
哦 那估计还跟gitlab不太一样 
我这个部署的时候 链接到仓库有ssh和https方法
跟本地一样可以用ssh链接 我不知道能不能共用账户key 我是重新生成的deploy key

**Comment by wafer-li** [comment]
看了一下，好像 deploy key 还是有好处的，似乎可以把权限的范围直接限制在 repo 中，而不是账户权限。

**Comment by wafer-li** [comment]
找了位大牛帮我把脚本重写了一下，目前只需要一条命令即可：

```
git ls-files -z | while read -d '' path; do touch -d "$(git log -1 --format="@%ct" "$path")" "$path"; done
```

在 Travis CI 配置里面可能需要用双引号括住，并转义其中的双引号

```yml
before_install:
    # Restore last modified time
    - "git ls-files -z | while read -d '' path; do touch -d \"$(git log -1 --format=\"@%ct\" \"$path\")\" \"$path\"; done"
```

**Comment by sli1989** [comment]
麻烦问问，你有没有用livere呀，评论的返回地址都是404页面，不知道遇到过没。

**Comment by wafer-li** [comment]
没有，我用的是 disqus，不好意思

**Comment by sli1989** [comment]
好的，谢谢。

**Comment by sli1989** [comment]
再请教个问题
按照你的方法 恢复了部分更新日期
不过 部署到coding的时候出现下面问题 不过不影响部署
查看了相关[issues](https://gitlab.com/gitlab-org/gitlab-ce/issues/14357) 看不懂
你知道啥原因吗

```
Warning: Permanently added 'git.coding.net,123.59.86.145' (RSA) to the list of known hosts.
remote: error: The last gc run reported the following. Please correct the root cause        
remote: and remove gc.log.        
remote: Automatic cleanup will not be performed until the file is removed.        
remote: 
remote: warning: There are too many unreachable loose objects; run 'git prune' to remove them.        
remote: 
To git@git.coding.net:sli1989/sli1989.git
```

**Comment by wafer-li** [comment]
这个其实我也不是很清楚……
但是我看到 GitHub 没问题我就没管……

**Comment by sli1989** [comment]
嗯，那就算了，谢谢。
